name: CD

on:
  push:
    branches: [ main, master, product]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: verify maven installation
        run: mvn -version

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
        if: failure()

      - name: build file with maven
        uses: mvn clean package -DskipTests

      - name: run application by maven
        uses: mvn springboot:run