name: CD

on:
  push:
    branches: [ main, master, product]
  pull_request:
    branches: [ master, main ]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: verify maven installation
        run: mvn -version

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
        if: failure()


      - name: build file with maven
        run: mvn clean package -DskipTests

      - name: run application by maven
        run: | 
          cd target
          nohup java -jar my-app-0.0.1.jar > app.log 2>&1 &
          sleep 10
          curl -I http://localhost:8080/actuator/health || (echo "Application can not run" && exit 1)

      - name: Show log if error
        if: failure()
        run: cat app.log
