name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: verify maven installation
        run: mvn -version

      - name: setup maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 4.0.0
        if: failure()

      - name: run test
        run: mvn clean install